"""Schemas package exporting domain and API models."""

from app.schemas.api import (
    AnalyzeRequest,
    AnalyzeResponse,
    ChatCitation,
    ChatMessage,
    ChatRequest,
    ChatResponse,
    DeductionResult,
    OCRUploadResponse,
    SchemeResult,
    SimulateRequest,
    SimulateResponse,
)
from app.schemas.domain import (
    DeductionDetails,
    DocumentData,
    DocumentType,
    Expenses,
    Income,
    IncomeDetails,
    Investments,
    RuleCategory,
    RuleResult,
    TaxDocument,
    TaxProfile,
    TaxRegime,
)

__all__ = [
    "Income",
    "Expenses",
    "Investments",
    "TaxDocument",
    "TaxProfile",
    "DocumentData",
    "RuleResult",
    "TaxRegime",
    "DocumentType",
    "RuleCategory",
    "IncomeDetails",
    "DeductionDetails",
    "ChatRequest",
    "ChatResponse",
    "ChatMessage",
    "ChatCitation",
    "AnalyzeRequest",
    "AnalyzeResponse",
    "DeductionResult",
    "SchemeResult",
    "OCRUploadResponse",
    "SimulateRequest",
    "SimulateResponse",
]
