"""ReportLab PDF filing summary generator for tax analyses."""

from io import BytesIO
from typing import Optional, List, Dict, Any
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch

from app.schemas.domain import TaxProfile
from app.schemas.api import AnalyzeResponse


def draw_page_decorations(canvas, doc):
    """Draw professional headers, footers, and page numbers on the canvas."""
    canvas.saveState()
    canvas.setFont('Helvetica', 8)
    canvas.setFillColor(colors.HexColor('#718096'))
    
    # Header decoration (only on pages after the first page if needed, or all pages)
    canvas.setStrokeColor(colors.HexColor('#CBD5E0'))
    canvas.setLineWidth(0.5)
    canvas.line(40, 750, 572, 750)
    canvas.drawString(40, 755, "consulTax Tax Filing Summary Report")
    
    # Footer decoration
    canvas.line(40, 50, 572, 50)
    canvas.drawString(40, 38, "Confidential - Tax optimization assessment generated by consulTax.")
    canvas.drawRightString(572, 38, f"Page {doc.page}")
    canvas.restoreState()


def generate_filing_summary_pdf(
    profile: TaxProfile,
    analysis: AnalyzeResponse,
    explanation: Optional[str] = None
) -> bytes:
    """
    Generates a structured, beautifully styled PDF summary report of tax calculations
    and savings using ReportLab and returns it as a bytes buffer.
    """
    buffer = BytesIO()
    
    # Document dimensions: Letter is 612 x 792 points. Margins: 40 points on sides, 60 top/bottom.
    # Usable width: 532 points.
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=40,
        rightMargin=40,
        topMargin=60,
        bottomMargin=60
    )
    
    styles = getSampleStyleSheet()
    
    # Custom styles mapping to our brand palette
    primary_color = colors.HexColor('#1A365D') # Corporate dark blue
    secondary_color = colors.HexColor('#2B6CB0') # Accent blue
    text_color = colors.HexColor('#2D3748') # Dark charcoal
    green_accent = colors.HexColor('#276749') # Deep forest green for savings
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=22,
        textColor=primary_color,
        spaceAfter=4
    )
    
    subtitle_style = ParagraphStyle(
        'DocSub',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        textColor=colors.HexColor('#4A5568'),
        spaceAfter=15
    )
    
    section_h1 = ParagraphStyle(
        'SectionH1',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=14,
        textColor=primary_color,
        spaceBefore=12,
        spaceAfter=6,
        keepWithNext=True
    )
    
    body_style = ParagraphStyle(
        'BodyTextCustom',
        parent=styles['BodyText'],
        fontName='Helvetica',
        fontSize=9.5,
        textColor=text_color,
        leading=14
    )
    
    cell_style = ParagraphStyle(
        'CellText',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        textColor=text_color,
        leading=12
    )
    
    cell_bold = ParagraphStyle(
        'CellBold',
        parent=cell_style,
        fontName='Helvetica-Bold'
    )
    
    cell_right = ParagraphStyle(
        'CellRight',
        parent=cell_style,
        alignment=2 # Right align
    )
    
    cell_right_bold = ParagraphStyle(
        'CellRightBold',
        parent=cell_bold,
        alignment=2
    )
    
    story = []
    
    # 1. Header Banner
    story.append(Paragraph("consulTax Filing Summary", title_style))
    story.append(Paragraph(f"Tax Assessment Year: {profile.assessment_year} (Financial Year: {profile.financial_year})", subtitle_style))
    story.append(Spacer(1, 10))
    
    # 2. Recommended Regime Card
    rec_regime = (analysis.recommended_regime.value if analysis.recommended_regime else "new").upper()
    savings = analysis.potential_savings or 0.0
    
    rec_data = [
        [
            Paragraph("<b>RECOMMENDED REGIME:</b>", ParagraphStyle('RecLabel', parent=cell_style, fontName='Helvetica-Bold', fontSize=10, textColor=colors.white)),
            Paragraph(f"<b>{rec_regime} TAX REGIME</b>", ParagraphStyle('RecVal', parent=cell_style, fontName='Helvetica-Bold', fontSize=10, textColor=colors.white))
        ],
        [
            Paragraph("<b>POTENTIAL TAX SAVINGS:</b>", ParagraphStyle('SaveLabel', parent=cell_style, fontName='Helvetica-Bold', fontSize=10, textColor=colors.white)),
            Paragraph(f"<b>₹{savings:,.2f}</b>", ParagraphStyle('SaveVal', parent=cell_style, fontName='Helvetica-Bold', fontSize=10, textColor=colors.white))
        ]
    ]
    rec_table = Table(rec_data, colWidths=[200, 332])
    rec_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), green_accent),
        ('PADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('LINEBELOW', (0, 0), (-1, 0), 0.5, colors.HexColor('#2F855A')),
    ]))
    story.append(rec_table)
    story.append(Spacer(1, 15))
    
    # 3. Taxpayer Information
    story.append(Paragraph("Taxpayer Information", section_h1))
    info_data = [
        [Paragraph("Profile ID", cell_bold), Paragraph(profile.profile_id or "N/A", cell_style),
         Paragraph("Age / Senior Citizen", cell_bold), Paragraph(f"{profile.age or 'N/A'} / {'Yes' if profile.is_senior_citizen else 'No'}", cell_style)],
        [Paragraph("Residential Status", cell_bold), Paragraph(profile.residential_status.title(), cell_style),
         Paragraph("Default Regime Pref", cell_bold), Paragraph(profile.regime_preference.value.upper(), cell_style)]
    ]
    info_table = Table(info_data, colWidths=[120, 146, 120, 146])
    info_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#EDF2F7')),
        ('BACKGROUND', (2, 0), (2, -1), colors.HexColor('#EDF2F7')),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('PADDING', (0, 0), (-1, -1), 6),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))
    story.append(info_table)
    story.append(Spacer(1, 15))
    
    # 4. Income Details
    story.append(Paragraph("Income Summary Breakdown", section_h1))
    inc = profile.income
    income_data = [
        [Paragraph("Income Head / Stream", cell_bold), Paragraph("Claimed Amount (₹)", cell_right_bold)],
        [Paragraph("Salary Income", cell_style), Paragraph(f"{inc.salary:,.2f}", cell_right)],
        [Paragraph("House Property (Rental) Income", cell_style), Paragraph(f"{inc.house_property:,.2f}", cell_right)],
        [Paragraph("Short-Term Capital Gains (STCG)", cell_style), Paragraph(f"{inc.capital_gains_short_term:,.2f}", cell_right)],
        [Paragraph("Long-Term Capital Gains (LTCG)", cell_style), Paragraph(f"{inc.capital_gains_long_term:,.2f}", cell_right)],
        [Paragraph("Business & Profession Income", cell_style), Paragraph(f"{inc.business_profession:,.2f}", cell_right)],
        [Paragraph("Income from Other Sources", cell_style), Paragraph(f"{inc.other_sources:,.2f}", cell_right)],
        [Paragraph("<b>Gross Total Income (GTI)</b>", cell_bold), Paragraph(f"<b>₹{profile.gross_total_income:,.2f}</b>", cell_right_bold)]
    ]
    income_table = Table(income_data, colWidths=[350, 182])
    income_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (1, 0), colors.HexColor('#1A365D')),
        ('TEXTCOLOR', (0, 0), (1, 0), colors.white),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#EDF2F7')),
        ('PADDING', (0, 0), (-1, -1), 6),
        ('ROWBACKGROUNDS', (0, 1), (-1, -2), [colors.white, colors.HexColor('#F7FAFC')]),
    ]))
    # Adjust headers styling
    income_data[0][0] = Paragraph("<b>Income Head / Stream</b>", ParagraphStyle('H1', parent=cell_bold, textColor=colors.white))
    income_data[0][1] = Paragraph("<b>Claimed Amount (₹)</b>", ParagraphStyle('H2', parent=cell_right_bold, textColor=colors.white))
    story.append(income_table)
    story.append(Spacer(1, 15))
    
    # 5. Deductions Applied
    story.append(Paragraph("Deductions & Exemptions Claimed", section_h1))
    dec = profile.deductions
    deductions_data = [
        [Paragraph("Deduction Section", cell_bold), Paragraph("Claimed (₹)", cell_right_bold), Paragraph("Eligible (₹)", cell_right_bold)],
        [Paragraph("Standard Deduction", cell_style), Paragraph(f"{dec.standard_deduction:,.2f}", cell_right), Paragraph(f"{dec.standard_deduction:,.2f}", cell_right)],
        [Paragraph("Section 80C (PPF/ELSS/FD)", cell_style), Paragraph(f"{dec.section_80c:,.2f}", cell_right), Paragraph(f"{dec.section_80c:,.2f}", cell_right)],
        [Paragraph("Section 80D (Health Insurance)", cell_style), Paragraph(f"{dec.section_80d:,.2f}", cell_right), Paragraph(f"{dec.section_80d:,.2f}", cell_right)],
        [Paragraph("Section 80CCD(1B) (NPS Self)", cell_style), Paragraph(f"{dec.section_80ccd_1b:,.2f}", cell_right), Paragraph(f"{dec.section_80ccd_1b:,.2f}", cell_right)],
        [Paragraph("Section 80CCD(2) (Employer NPS)", cell_style), Paragraph(f"{dec.section_80ccd_2:,.2f}", cell_right), Paragraph(f"{dec.section_80ccd_2:,.2f}", cell_right)],
        [Paragraph("Section 24(b) (Home Loan Interest)", cell_style), Paragraph(f"{dec.section_24b:,.2f}", cell_right), Paragraph(f"{dec.section_24b:,.2f}", cell_right)],
        [Paragraph("Section 10(13A) (HRA Exemption)", cell_style), Paragraph(f"{dec.hra_exemption:,.2f}", cell_right), Paragraph(f"{dec.hra_exemption:,.2f}", cell_right)],
        [Paragraph("<b>Total Deductions Applied</b>", cell_bold), Paragraph(f"<b>₹{profile.total_deductions:,.2f}</b>", cell_right_bold), Paragraph(f"<b>₹{profile.total_deductions:,.2f}</b>", cell_right_bold)]
    ]
    
    deductions_data[0][0] = Paragraph("<b>Deduction Section</b>", ParagraphStyle('D1', parent=cell_bold, textColor=colors.white))
    deductions_data[0][1] = Paragraph("<b>Claimed (₹)</b>", ParagraphStyle('D2', parent=cell_right_bold, textColor=colors.white))
    deductions_data[0][2] = Paragraph("<b>Eligible (₹)</b>", ParagraphStyle('D3', parent=cell_right_bold, textColor=colors.white))
    
    deductions_table = Table(deductions_data, colWidths=[250, 141, 141])
    deductions_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1A365D')),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#EDF2F7')),
        ('PADDING', (0, 0), (-1, -1), 6),
        ('ROWBACKGROUNDS', (0, 1), (-1, -2), [colors.white, colors.HexColor('#F7FAFC')]),
    ]))
    story.append(deductions_table)
    story.append(Spacer(1, 15))
    
    # 6. Comparative Regime Analysis
    story.append(PageBreak()) # Clean page boundary for the comparison tables and explanation
    story.append(Paragraph("Comparative Tax Regime Analysis", section_h1))
    
    # Get values from analysis response if available
    old_liab = analysis.old_regime_liability or 0.0
    new_liab = analysis.new_regime_liability or 0.0
    
    comp_data = [
        [Paragraph("Filing Metric", cell_bold), Paragraph("Old Tax Regime (₹)", cell_right_bold), Paragraph("New Tax Regime (₹)", cell_right_bold)],
        [Paragraph("Gross Total Income", cell_style), Paragraph(f"{profile.gross_total_income:,.2f}", cell_right), Paragraph(f"{profile.gross_total_income:,.2f}", cell_right)],
        [Paragraph("Total Deductions Allowed", cell_style), Paragraph(f"{profile.total_deductions:,.2f}", cell_right), Paragraph(f"{profile.total_deductions:,.2f}", cell_right)],
        [Paragraph("Net Taxable Income", cell_style), Paragraph(f"{profile.net_taxable_income:,.2f}", cell_right), Paragraph(f"{profile.net_taxable_income:,.2f}", cell_right)],
        [Paragraph("<b>Estimated Tax Liability</b>", cell_bold), Paragraph(f"<b>₹{old_liab:,.2f}</b>", cell_right_bold), Paragraph(f"<b>₹{new_liab:,.2f}</b>", cell_right_bold)]
    ]
    
    comp_data[0][0] = Paragraph("<b>Filing Metric</b>", ParagraphStyle('C1', parent=cell_bold, textColor=colors.white))
    comp_data[0][1] = Paragraph("<b>Old Tax Regime (₹)</b>", ParagraphStyle('C2', parent=cell_right_bold, textColor=colors.white))
    comp_data[0][2] = Paragraph("<b>New Tax Regime (₹)</b>", ParagraphStyle('C3', parent=cell_right_bold, textColor=colors.white))
    
    comp_table = Table(comp_data, colWidths=[200, 166, 166])
    comp_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1A365D')),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#E2E8F0')),
        ('PADDING', (0, 0), (-1, -1), 8),
        # Highlight recommended regime column
        ('BACKGROUND', (1, -1), (1, -1), colors.HexColor('#FED7D7') if rec_regime == "NEW" else colors.HexColor('#C6F6D5')),
        ('BACKGROUND', (2, -1), (2, -1), colors.HexColor('#C6F6D5') if rec_regime == "NEW" else colors.HexColor('#FED7D7')),
    ]))
    story.append(comp_table)
    story.append(Spacer(1, 15))
    
    # 7. AI Explanation Summary
    if explanation:
        story.append(Paragraph("Tax Planner Notes & Explanations", section_h1))
        # Format text to clean paragraph style. Split by newlines.
        para_texts = explanation.split("\n")
        for para in para_texts:
            clean_para = para.strip().replace("**", "")
            if clean_para.startswith("### "):
                story.append(Paragraph(f"<b>{clean_para[4:]}</b>", ParagraphStyle('ExplHead', parent=body_style, fontName='Helvetica-Bold', fontSize=11, spaceBefore=4, spaceAfter=2)))
            elif clean_para.startswith("- ") or clean_para.startswith("* "):
                story.append(Paragraph(f"&bull; {clean_para[2:]}", ParagraphStyle('ExplBullet', parent=body_style, leftIndent=12, spaceAfter=2)))
            elif clean_para:
                story.append(Paragraph(clean_para, ParagraphStyle('ExplPara', parent=body_style, spaceAfter=6)))
                
    # Build Document
    doc.build(story, onFirstPage=draw_page_decorations, onLaterPages=draw_page_decorations)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
